-- MySQL Script generated by MySQL Workbench
-- Thu Sep 15 22:36:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ordem_servico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ordem_servico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ordem_servico` DEFAULT CHARACTER SET utf8 ;
USE `ordem_servico` ;

-- -----------------------------------------------------
-- Table `ordem_servico`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordem_servico`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `contato` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordem_servico`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordem_servico`.`veiculo` (
  `idveiculo` INT NOT NULL AUTO_INCREMENT,
  `cliente_idcliente` INT NOT NULL,
  `placa` VARCHAR(45) NULL,
  `fabricante` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `cor` VARCHAR(45) NULL,
  PRIMARY KEY (`idveiculo`),
  INDEX `fk_veiculo_cliente_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_veiculo_cliente`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `ordem_servico`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordem_servico`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordem_servico`.`servico` (
  `idservico` INT NOT NULL AUTO_INCREMENT,
  `nome_servico` VARCHAR(45) NULL,
  `duracao_horas` FLOAT NULL,
  `valor_servico` FLOAT NULL,
  PRIMARY KEY (`idservico`),
  UNIQUE INDEX `nome_servico_UNIQUE` (`nome_servico` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordem_servico`.`peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordem_servico`.`peca` (
  `idpeca` INT NOT NULL AUTO_INCREMENT,
  `nome_peca` VARCHAR(45) NULL,
  `valor_peca` FLOAT NULL,
  PRIMARY KEY (`idpeca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordem_servico`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordem_servico`.`equipe` (
  `idequipe` INT NOT NULL AUTO_INCREMENT,
  `nome_equipe` VARCHAR(45) NULL,
  PRIMARY KEY (`idequipe`),
  UNIQUE INDEX `nome_equipe_UNIQUE` (`nome_equipe` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordem_servico`.`mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordem_servico`.`mecanico` (
  `idmecanico` INT NOT NULL AUTO_INCREMENT,
  `codigo` INT NULL,
  `nome` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `especialidade` VARCHAR(45) NULL,
  `equipe_idequipe` INT NOT NULL,
  PRIMARY KEY (`idmecanico`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE,
  INDEX `fk_mecanico_equipe1_idx` (`equipe_idequipe` ASC) VISIBLE,
  CONSTRAINT `fk_mecanico_equipe1`
    FOREIGN KEY (`equipe_idequipe`)
    REFERENCES `ordem_servico`.`equipe` (`idequipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordem_servico`.`os`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordem_servico`.`os` (
  `idos` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NULL,
  `data_emissao` DATE NULL,
  `valor` FLOAT NULL,
  `satus` ENUM('Em Espera', 'Em Orcamento', 'Em Manutenção', 'Finalizado') NULL,
  `data_conclusao` DATE NULL,
  `oscol` VARCHAR(45) NULL,
  `veiculo_idveiculo` INT NOT NULL,
  `equipe_idequipe` INT NOT NULL,
  `tipo_os` ENUM('Revisao', 'Reparo') NULL,
  PRIMARY KEY (`idos`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC) VISIBLE,
  INDEX `fk_os_veiculo1_idx` (`veiculo_idveiculo` ASC) VISIBLE,
  INDEX `fk_os_equipe1_idx` (`equipe_idequipe` ASC) VISIBLE,
  CONSTRAINT `fk_os_veiculo1`
    FOREIGN KEY (`veiculo_idveiculo`)
    REFERENCES `ordem_servico`.`veiculo` (`idveiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_os_equipe1`
    FOREIGN KEY (`equipe_idequipe`)
    REFERENCES `ordem_servico`.`equipe` (`idequipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordem_servico`.`executa_os`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordem_servico`.`executa_os` (
  `peca_idpeca` INT NOT NULL,
  `os_idos` INT NOT NULL,
  `servico_idservico` INT NOT NULL,
  PRIMARY KEY (`peca_idpeca`, `os_idos`, `servico_idservico`),
  INDEX `fk_peca_has_os_os1_idx` (`os_idos` ASC) VISIBLE,
  INDEX `fk_peca_has_os_peca1_idx` (`peca_idpeca` ASC) VISIBLE,
  INDEX `fk_peca_has_os_servico1_idx` (`servico_idservico` ASC) VISIBLE,
  CONSTRAINT `fk_peca_has_os_peca1`
    FOREIGN KEY (`peca_idpeca`)
    REFERENCES `ordem_servico`.`peca` (`idpeca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peca_has_os_os1`
    FOREIGN KEY (`os_idos`)
    REFERENCES `ordem_servico`.`os` (`idos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peca_has_os_servico1`
    FOREIGN KEY (`servico_idservico`)
    REFERENCES `ordem_servico`.`servico` (`idservico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
